/**
 * The levels, and what walks them.
 *
 * A level is a board (generated by `tools/gen-scene.mjs` from a polyline), a
 * wave table, and a ground feel. Everything that makes one level different from
 * another lives here; `main.ts` plays whichever one it is handed.
 *
 * The three of them are deliberately different PROBLEMS rather than the same
 * problem with bigger numbers:
 *
 *  - Meadow is long and open. The road is 36 cells, so anything you build gets
 *    a lot of time with anything that walks past it, and there are 74 places to
 *    build. It is the board on which the game is learned.
 *  - Frostfall is 25 cells and the ground is ice. The same wave is worse here
 *    because the towers get a third less time with it, and the hero cannot stop
 *    on a coin.
 *  - Crossroads puts the two gates on opposite walls. Nothing covers both, and
 *    neither can you.
 *
 * The hit points are MEASURED, not chosen — `verify-3d-balance.mjs` plays each
 * board with a fixed competent strategy and reports where it gets to. See
 * CLAUDE.md for what that has found.
 */

export interface Wave {
  count: number; hp: number; speed: number; model: string; bounty: number;
  /** Whether this kind shoots back. */
  armed: boolean;
  /** The kit's UFOs are a full tile wide; this is how big they read next to
   *  a 0.72-tall hero. */
  scale: number;
  /** Walks on the ground rather than flying over it. Rigged models only — a
   *  UFO set down at y=0 looks parked. */
  ground?: boolean;
  /** Turns to face the way it is going, instead of spinning like a saucer. */
  facesTravel?: boolean;
  /** What it throws. Defaults to the small bullet everything else fires. */
  ammo?: string;
  /** Hearts per hit. Defaults to 1. */
  damage?: number;
  /** Announced, health bar always up, and the wave is over when it falls. */
  boss?: boolean;
  /** Shown on the banner when it arrives. */
  label?: string;
}

/** A boss, sized to the level it ends. One of them, walking, on the ground,
 *  throwing boulders with a tell you can see from across the board. It is the
 *  only enemy in the game that is not a saucer. */
const boss = (hp: number, bounty: number, label: string): Wave => ({
  count: 1, hp, speed: 0.62, model: 'boss-orc', bounty, armed: true, scale: 2.1,
  ground: true, facesTravel: true, ammo: 'td-ammo-boulder', damage: 2, boss: true, label,
});

export interface LevelDef {
  id: string;
  name: string;
  /** One line, shown on the door in the hub. Not a paragraph. */
  blurb: string;
  waves: Wave[];
  startGold: number;
  lives: number;
  /** Seconds between enemies in a wave, and between waves. */
  spawnGap: number;
  waveGap: number;
  /** How long before the first wave. Longer on the short boards, where the
   *  towers get less time with everything that walks past them. */
  firstWaveDelay: number;
  /** How many towers you may have standing at once.
   *
   *  Without a cap the game has one strategy: buy the cheapest tower, forever.
   *  A ballista is 25g for 2 damage a second and its first upgrade is 20g for
   *  1.4 more, so another tower is strictly better than a better tower right up
   *  until the board runs out of ground — and a measured run put FIFTY level-one
   *  ballistas on Meadow and lost nothing. With a cap, the gold has somewhere
   *  else to go and the question becomes which stretch of road you are covering.
   */
  maxTowers: number;
  /** How much the ground lets go. 0 is dry, 1 would be uncontrollable; snow is
   *  0.55, which is enough that you overshoot a build spot and have to come
   *  back but not enough to stop you fighting. */
  slip: number;
}

export const LEVELS: LevelDef[] = [
  {
    id: 'meadow',
    name: 'Meadow',
    blurb: 'Open ground',
    startGold: 60,
    lives: 10,
    spawnGap: 1.1,
    waveGap: 6,
    firstWaveDelay: 3,
    maxTowers: 12,
    slip: 0,
    waves: [
      { count: 6, hp: 10, speed: 1.1, model: 'td-ufo-a', bounty: 9, armed: true, scale: 0.62 },
      { count: 8, hp: 16, speed: 1.25, model: 'td-ufo-b', bounty: 11, armed: true, scale: 0.62 },
      { count: 10, hp: 14, speed: 2.1, model: 'td-ufo-c', bounty: 12, armed: true, scale: 0.5 },
      { count: 10, hp: 42, speed: 1.2, model: 'td-ufo-a2', bounty: 15, armed: true, scale: 0.68 },
      { count: 12, hp: 66, speed: 1.3, model: 'td-ufo-d', bounty: 18, armed: true, scale: 0.72 },
      { count: 14, hp: 58, speed: 1.9, model: 'td-ufo-b2', bounty: 20, armed: true, scale: 0.6 },
      { count: 14, hp: 115, speed: 1.2, model: 'td-ufo-c2', bounty: 25, armed: true, scale: 0.78 },
      boss(1400, 180, 'THE SCOUT WARLORD'),
    ],
  },
  {
    id: 'frostfall',
    name: 'Frostfall',
    blurb: 'Ice underfoot',
    startGold: 140,
    lives: 12,
    spawnGap: 1.15,
    waveGap: 7,
    maxTowers: 14,
    // Four times Meadow's, because of where the road STARTS. The hero arrives
    // through the exit door at the top of every board; Meadow's spawn tile is
    // a few steps from it and Frostfall's is in the opposite corner, so the
    // opening here is a walk across the map before a single tower goes down —
    // on ice. Measured: eight of ten lives gone in wave one, then four.
    firstWaveDelay: 13,
    slip: 0.55,
    waves: [
      { count: 6, hp: 13, speed: 1.1, model: 'td-ufo-b', bounty: 13, armed: true, scale: 0.62 },
      { count: 8, hp: 21, speed: 1.25, model: 'td-ufo-a2', bounty: 15, armed: true, scale: 0.68 },
      { count: 10, hp: 19, speed: 2.0, model: 'td-ufo-c', bounty: 16, armed: true, scale: 0.5 },
      { count: 10, hp: 48, speed: 1.25, model: 'td-ufo-d', bounty: 19, armed: true, scale: 0.72 },
      { count: 12, hp: 62, speed: 1.95, model: 'td-ufo-b2', bounty: 21, armed: true, scale: 0.6 },
      { count: 12, hp: 112, speed: 1.2, model: 'td-ufo-c2', bounty: 25, armed: true, scale: 0.78 },
      { count: 14, hp: 150, speed: 1.4, model: 'td-ufo-d2', bounty: 28, armed: true, scale: 0.85 },
      { count: 16, hp: 178, speed: 2.0, model: 'td-ufo-c', bounty: 28, armed: true, scale: 0.55 },
      { count: 16, hp: 235, speed: 1.3, model: 'td-ufo-a2', bounty: 30, armed: true, scale: 0.75 },
      boss(2000, 260, 'THE FROST WARLORD'),
    ],
  },
  {
    id: 'crossroads',
    name: 'Crossroads',
    blurb: 'Two gates, far apart',
    startGold: 150,
    lives: 12,
    spawnGap: 1.05,
    waveGap: 6,
    // Its road is 22 cells — the shortest of the three — so everything walks it
    // in about twenty seconds and the towers get one pass each. A short road is
    // what makes this board hard; it must not also make the first wave
    // unsurvivable, and it did: nine of twelve lives gone before a second tower
    // was up.
    firstWaveDelay: 12,
    maxTowers: 14,
    slip: 0,
    waves: [
      { count: 8, hp: 18, speed: 1.2, model: 'td-ufo-a2', bounty: 14, armed: true, scale: 0.68 },
      { count: 10, hp: 28, speed: 1.3, model: 'td-ufo-d', bounty: 16, armed: true, scale: 0.72 },
      { count: 12, hp: 26, speed: 2.1, model: 'td-ufo-c', bounty: 17, armed: true, scale: 0.5 },
      { count: 12, hp: 54, speed: 1.25, model: 'td-ufo-c2', bounty: 21, armed: true, scale: 0.78 },
      { count: 14, hp: 70, speed: 2.0, model: 'td-ufo-b2', bounty: 23, armed: true, scale: 0.6 },
      { count: 14, hp: 100, speed: 1.4, model: 'td-ufo-d2', bounty: 27, armed: true, scale: 0.85 },
      { count: 16, hp: 135, speed: 2.0, model: 'td-ufo-c', bounty: 29, armed: true, scale: 0.55 },
      { count: 16, hp: 170, speed: 1.3, model: 'td-ufo-a2', bounty: 32, armed: true, scale: 0.75 },
      { count: 18, hp: 215, speed: 1.85, model: 'td-ufo-b2', bounty: 36, armed: true, scale: 0.65 },
      { count: 18, hp: 280, speed: 1.4, model: 'td-ufo-d2', bounty: 40, armed: true, scale: 0.9 },
      { count: 20, hp: 360, speed: 1.5, model: 'td-ufo-c2', bounty: 46, armed: true, scale: 0.85 },
      boss(3200, 400, 'THE WARLORD'),
    ],
  },
];
